// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubgStatsDiscordBot.Helpers;

namespace PubgStatsDiscordBot.Migrations
{
    [DbContext(typeof(PubgDbContext))]
    [Migration("20190828155223_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PubgStatsDiscordBot.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CurrentSeasionLastUpdate");

                    b.Property<string>("DuoStatsID");

                    b.Property<string>("Name");

                    b.Property<string>("SoloStatsID");

                    b.Property<string>("SquadStatsID");

                    b.HasKey("Id");

                    b.HasIndex("DuoStatsID");

                    b.HasIndex("SoloStatsID");

                    b.HasIndex("SquadStatsID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PubgStatsDiscordBot.Models.Stats", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Assists");

                    b.Property<float>("BestRankPoint");

                    b.Property<int>("DailyKills");

                    b.Property<int>("DailyWins");

                    b.Property<float>("DamageDealt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("HeadshotKills");

                    b.Property<int>("Kills");

                    b.Property<float>("LongestKill");

                    b.Property<int>("Losses");

                    b.Property<int>("MaxKillStreaks");

                    b.Property<float>("RankPoints");

                    b.Property<int>("RoundsPlayed");

                    b.Property<int>("Top10s");

                    b.Property<int>("WeeklyKills");

                    b.Property<int>("WeeklyWins");

                    b.Property<int>("Wins");

                    b.HasKey("ID");

                    b.ToTable("Stats");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Stats");
                });

            modelBuilder.Entity("PubgStatsDiscordBot.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiscordName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PubgStatsDiscordBot.Models.Match", b =>
                {
                    b.HasBaseType("PubgStatsDiscordBot.Models.Stats");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("Duration");

                    b.Property<int>("GameMode");

                    b.Property<bool>("IsCustomMatch");

                    b.Property<int>("MapName");

                    b.Property<string>("MatchId");

                    b.Property<string>("PlayerID");

                    b.HasIndex("PlayerID");

                    b.HasDiscriminator().HasValue("Match");
                });

            modelBuilder.Entity("PubgStatsDiscordBot.Models.Player", b =>
                {
                    b.HasOne("PubgStatsDiscordBot.Models.Stats", "DuoStats")
                        .WithMany()
                        .HasForeignKey("DuoStatsID");

                    b.HasOne("PubgStatsDiscordBot.Models.Stats", "SoloStats")
                        .WithMany()
                        .HasForeignKey("SoloStatsID");

                    b.HasOne("PubgStatsDiscordBot.Models.Stats", "SquadStats")
                        .WithMany()
                        .HasForeignKey("SquadStatsID");
                });

            modelBuilder.Entity("PubgStatsDiscordBot.Models.Match", b =>
                {
                    b.HasOne("PubgStatsDiscordBot.Models.Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerID");
                });
#pragma warning restore 612, 618
        }
    }
}
